### ISSUE TITLE
Periode for videresending

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMvideresending_festival#5]
Videresending til UKM-festivalen bør være åpen i en gitt periode, ikke fra mønstringen er registrert og til påmeldingsfristen

**Comment by AsgeirSH** [comment]
Samme strategi kan brukes på denne, altså deadline2? I så fall relativt quick fix.

**Comment by mariusmandal** [comment]
quickfix er bra :+1:

**Comment by mariusmandal** [comment]
@AsgeirSH Husker du om du fiksa denne?

**Comment by AsgeirSH** [comment]
@mariusmandal Ikke fiksa, nei.

Sendt fra min iPad

**Comment by AsgeirSH** [comment]
Det burde i teorien holde å legge til funksjonen `monstring->subscriptionOpened` i API og bruke den i videresendinga.

``` php
public function subscriptionOpened() {
    return time() > $this->info['pl_deadline2'];
}
```

Alternativt (enda enklere/bedre?) kunne `monstring->subscribable` skrives om slik, men ~~det gir mindre fleksibel tilbakemelding.~~ den er egentlig implementert som isDeadlinePassed pdd. Det kan føre til krasj om den endres.

``` php
public function subscribable($deadline = 'pl_deadline') {
    return (time() > $this->info['pl_deadline2']) && ($this->info[$deadline] > time());
}
```

**Comment by mariusmandal** [comment]
Subscribable burde kanskje håndtere det, men den må da switche mellom lokal-mønstringer og andre mønstringer (land+fylke). Kanskje burde vi finne bedre navn og lage dette som flere funksjoner;
1: er lokalmønstringen åpen for påmelding for
1a: innslag med tittel
1b: innslag uten tittel
2: er fylkes-/landsmønstringen åpen for videresending

**Comment by AsgeirSH** [comment]
Fix krever update av UKMapi
